"""empty message

Revision ID: 2fff050fced8
Revises: 
Create Date: 2022-01-19 12:55:25.628899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fff050fced8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carro',
    sa.Column('create_time', sa.String(), nullable=True),
    sa.Column('update_time', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('placa', sa.String(length=7), nullable=True),
    sa.Column('modelo', sa.String(length=15), nullable=True),
    sa.Column('cor', sa.String(length=15), nullable=True),
    sa.Column('ano', sa.String(length=4), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moto',
    sa.Column('create_time', sa.String(), nullable=True),
    sa.Column('update_time', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('placa', sa.String(length=7), nullable=True),
    sa.Column('modelo', sa.String(length=15), nullable=True),
    sa.Column('cor', sa.String(length=15), nullable=True),
    sa.Column('ano', sa.String(length=4), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('create_time', sa.String(), nullable=True),
    sa.Column('update_time', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.Column('nascimento', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart',
    sa.Column('create_time', sa.String(), nullable=True),
    sa.Column('update_time', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cupom',
    sa.Column('create_time', sa.String(), nullable=True),
    sa.Column('update_time', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('desconto_carro', sa.Integer(), nullable=True),
    sa.Column('desconto_moto', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_car',
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('qtd', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['carro.id'], ),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], )
    )
    op.create_table('cart_moto',
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('moto_id', sa.Integer(), nullable=True),
    sa.Column('qtd', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['moto_id'], ['moto.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_moto')
    op.drop_table('cart_car')
    op.drop_table('cupom')
    op.drop_table('cart')
    op.drop_table('user')
    op.drop_table('moto')
    op.drop_table('carro')
    # ### end Alembic commands ###
